<?php 
if(Mage::getSingleton('customer/session')->isLoggedIn()) 
{
	$module2= $this->showJoin();
	$module= $this->showpro();
//print_r($module); die();
}

?>
<center>
<div class="block block-poll">
    <div class="block-title">
        <strong><span><?php echo $this->__('Community Poll') ?></span></strong>
    </div>
	<?php foreach ($module2 as $data) {?>
	<b><p><?php echo $data['polling_id'] ?></b>.&nbsp &nbsp  <strong><?php echo $data['title'] ?></p></strong>
	<?php } ?>
	<form method="post" action="<?php echo Mage::getUrl('polling/index/submit'); ?>">
		<?php foreach ($module as $data1) {?>
		<div class="poll">    
			<ul class="poll-system">
				<li><div><b> <input type="radio" name="check" value="<?php echo $data1['answer_id']?>">&nbsp &nbsp <?php echo $data1['answer_title'] ?></b></li>        
			</ul>   
		</div> 
		<?php } ?>
	</br></br>
	<div class="buttons-set" >                    
	<button type="submit" class="button" name="sub" id="send2"><span><span><?php echo $this->__('Vote') ?></span></span></button>
	</div>
</form>
</div>
</center>


