<?php 

	$module2= $this->showJoin();
	$module= $this->showpro();
//print_r($module); die();


?>
<div class="block block-poll">
    <div class="block-title">
        <strong><span><?php echo $this->__('Community Poll') ?></span></strong>
    </div>
	<?php foreach ($module2 as $data) {?>
	<div class="question">
	<h5><b><?php echo $data['polling_id'] ?></b>.&nbsp &nbsp  <strong><?php echo $data['title'] ?></strong>
	<?php } ?></h5></div>
	<form method="post" action="<?php echo Mage::getUrl('polling/index/submit'); ?>">
		<?php foreach ($module as $data1) {?>
		<div class="poll">    
			<ul class="poll-system">
				<li><h6> <input type="radio" name="check" value="<?php echo $data1['answer_id']?>">&nbsp &nbsp <?php echo $data1['answer_title'] ?></h6></li>        
			</ul>   
		</div> 
		<?php } ?>
	</br></br>
	<div class="buttons-set" >                    
	<button type="submit" class="button" name="sub" id="send2"><span><span><?php echo $this->__('Vote') ?></span></span></button>
	</div>
</form>
</div>
