<?php 

$module2= $this->fetchQuestions();
$module= $this->fetchAnswers();
?>
<?php
$post = $this->getRequest()->getParams(); 
$percent=0;
foreach ($module as $value) {
	$percent= $percent + $value['votes_count'];
}
?>
<div class="block block-poll">	
<h2 align="center" class="rslt">Poll Results</h2>
	<?php foreach ($module2 as $data) {?>
	<div class="question">
		<ul class="poll-system">
			<h5><b><?php echo $data['polling_id'] ?></b>.&nbsp &nbsp  <strong><?php echo $data['title'] ?></strong>
				<?php } ?></h5>
			</ul>
		</div>
		<?php foreach ($module as $data1) {?>
		<ul class="poll-system">
			<li><h5><?php echo $data1['answer_title']; ?>&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;<b><?php echo $data1['votes_count']; ?></b>&nbsp;&nbsp;<b>(<?php echo round($data1['votes_count']/$percent*100, 2); ?>%)</b></br></h5></li>
		</ul>
		<?php } ?>
		
	</div>