<div>
	<div class="account-login">
		<div class="page-title">
			<h1><?php echo $this->__('Please enter your information') ?></h1>
		</div>
		<div class="content">
			<form method="post">
				<ul class="form-list">
					<li>
						<label align=" center" for="email" class="required"><em>*</em><?php echo $this->__('Name') ?></label>
						<div class="input-box">
							<input type="text" name="name" placeholder="Name">
						</div>
					</li>
					<li>
						<label align=" center" for="email" class="required"><em>*</em><?php echo $this->__('Age') ?></label>
						<div class="input-box">
							<input type="text" name="age" placeholder="Age">
						</div>
					</li>
					<li>
						<label align=" center" for="email" class="required"><em>*</em><?php echo $this->__('City') ?></label>
						<div class="input-box">
							<input type="text" name="city" placeholder="City">
						</div>
					</li>
					<li>
						<label align=" center" for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
						<div class="input-box">
							<input type="text" name="email" placeholder="Email">
						</div>
					</li>
					<li>
						<label align=" center" for="email" class="required"><em>*</em><?php echo $this->__('Contact No.') ?></label>
						<div class="input-box">
							<input type="text" name="contact" placeholder="Contact">
						</div>
					</li>
				</ul>
				<p class="required"><?php echo $this->__('* Required Fields') ?></p>					
				
			</div>
			<div class="buttons-set" >                    
				<button type="submit" class="button" name="sub" id="send2"><span><span><?php echo $this->__('Submit') ?></span></span></button>
			</div>
		</form>
	</div>
</div>

