<?php if($savedDetails = $this->getSavedDetails($this->getType())): ?>

<table width="100%">
    <?php foreach($savedDetails as $savedDetail): ?>
        <tr>
            <td width="60">
                <img src="<?php echo $this->getSkinUrl('images/gene/braintree/' . Gene_Braintree_Block_Creditcard::getCardIcon((isset($savedDetail->cardType) ? $savedDetail->cardType : 'paypal'))); ?>" />
            </td>
            <td>
                <?php if(isset($savedDetail->cardType)): ?>
                    xxxx - xxxx - xxxx - <?php echo $savedDetail->last4; ?> &nbsp;&nbsp;&nbsp; <em><?php echo $this->__('Expires:'); ?></em> <?php echo $savedDetail->expirationMonth; ?>/<?php echo $savedDetail->expirationYear; ?>
                <?php else: ?>
                    <?php echo $savedDetail->email; ?>
                <?php endif; ?>
            </td>
            <td>
                <a href="<?php echo $this->getUrl('*/*/remove', array('id' => $savedDetail->token)); ?>" onclick="if(!confirm('<?php echo $this->__('Are you sure you want to remove this payment method?'); ?>')) { return false }"><?php echo $this->__('Remove'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php endif; ?>