<?php
/* @var $this Gene_Braintree_Block_Paypal */
?>
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display: none;">

    <?php if($this->hasSavedDetails() && $this->getMethod()->isVaultEnabled()): ?>

        <label><?php echo $this->__('Linked Accounts'); ?></label>
        <p><?php echo $this->__('The following PayPal accounts are currently linked with your account.'); ?></p>
        <table width="100%" cellspacing="0" cellpadding="0" id="paypal-saved-accounts">
            <tbody>
                <?php
                $count = 0;
                foreach($this->getSavedDetails() as $savedDetail):
                    ?>
                    <tr valign="middle">
                        <td width="20"><input type="radio" name="payment[paypal_payment_method_token]" id="<?php echo $savedDetail->token; ?>" value="<?php echo $savedDetail->token; ?>"<?php echo ($count == 0 ? ' checked="checked"' : ''); ?>/></td>
                        <td valign="middle">
                            <label for="<?php echo $savedDetail->token; ?>" style="line-height: 48px;">
                                <img src="<?php echo $this->getSkinUrl('images/gene/braintree/PP.png') ?>" align="left" />
                                <span class="saved-paypal-email"><?php echo $savedDetail->email; ?></span>
                            </label>
                        </td>
                    </tr>
                    <?php
                    ++$count;
                endforeach; ?>
                <tr valign="middle" class="other-row">
                    <td width="20"><input type="radio" name="payment[paypal_payment_method_token]" id="other-paypal" value="other" /></td>
                    <td><label for="other-paypal"><?php echo $this->__('New PayPal Account'); ?></label></td>
                </tr>
            </tbody>
        </table>

    <?php endif; ?>

    <div class="paypal-info"<?php echo ($this->hasSavedDetails() && $this->getMethod()->isVaultEnabled() ? ' style="display: none;"' : ''); ?>>
        <p><?php echo $this->__('You will complete your payment via PayPal after the order review step.'); ?></p>

        <?php if($this->canSavePayPal()): ?>
            <input type="checkbox" title="<?php echo $this->__('Save this account for future use') ?>"
                   class="input-checkbox" id="gene_braintree_paypal_store_in_vault" name="payment[save_paypal]"
                   value="1"/>
            <label for="gene_braintree_paypal_store_in_vault" style="float:none;"><?php echo $this->__(
                    'Save this account for future use'
                ) ?></label>
        <?php endif; ?>

        <?php /* Our hidden field to store the payment nonce */ ?>
        <input type="hidden" name="payment[payment_method_nonce]" id="paypal-payment-nonce" />
    </div>

</div>

<!-- Attach an event onto all radio buttons -->
<script type="text/javascript">

    // Set a flag to determine whether the PayPal flag is initialized
    var PayPalInit = false;

    // Wrap our logic in a function so we can init in different ways
    initPayPal = function() {

        // Verify that vzero is defined before attempting to use it
        if (typeof vzeroPaypal !== 'undefined') {

            // Yay we're good to go
            PayPalInit = true;

            // Always set the amount as it's needed within 3D secure requests
            vzeroPaypal.setPricing('<?php echo Mage::helper('gene_braintree')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->collectTotals()->getGrandTotal()); ?>', '<?php echo Mage::getSingleton('checkout/cart')->getQuote()->getQuoteCurrencyCode(); ?>');
        }

        if(typeof vzero !== 'undefined') {
            vzero.paypalLoaded();
        }

    };

    // Init PayPal on load
    initPayPal();

    // If the function didn't run on the load of the payment method do it on dom:loaded
    if(!PayPalInit) {
        document.observe('dom:loaded', function () {
            initPayPal();
        });
    }

</script>