<?php
/* @var $this Gene_Braintree_Block_Creditcard */
$_code = $this->getMethodCode()
?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;" class="form-list">

    <?php if($this->hasSavedDetails() && $this->getMethod()->isVaultEnabled()): ?>

        <label><?php echo $this->__('Saved Cards'); ?></label><br />
        <p style="padding-left: 0;" class="saved-cards-intro"><?php echo $this->__('The following credit cards accounts are currently linked with your account.'); ?></p>
        <table cellspacing="0" cellpadding="0" id="creditcard-saved-accounts">
            <?php
            $count = 0;
            foreach($this->getSavedDetails() as $savedDetail):
                ?>
                <tr valign="middle">
                    <td width="20">
                        <?php if($this->getMethod()->is3DEnabled()): ?>
                            <input type="radio" name="payment[card_payment_method_token]" id="<?php echo $savedDetail->token; ?>" data-token="<?php echo $savedDetail->token; ?>" data-threedsecure-nonce="<?php echo $this->getMethod()->getThreeDSecureVaultNonce($savedDetail->token); ?>" value="threedsecure"<?php echo ($count == 0 ? ' checked="checked"' : ''); ?>/>
                        <?php else: ?>
                            <input type="radio" name="payment[card_payment_method_token]" id="<?php echo $savedDetail->token; ?>" value="<?php echo $savedDetail->token; ?>"<?php echo ($count == 0 ? ' checked="checked"' : ''); ?>/>
                        <?php endif; ?>
                    </td>
                    <td>
                        <label for="<?php echo $savedDetail->token; ?>">
                            <img src="<?php echo $this->getSkinUrl('images/gene/braintree/' . $this->getCardIcon($savedDetail->cardType)) ?>" align="left" />
                            <span class="saved-card-info">
                                <span class="saved-card-number">xxxx - xxxx - xxxx - <?php echo $savedDetail->last4; ?></span>
                                <span class="saved-expiry-date"><em><?php echo $this->__('Expires:'); ?></em> <?php echo $savedDetail->expirationMonth; ?>/<?php echo $savedDetail->expirationYear; ?></span>
                            </span>
                        </label>
                    </td>
                </tr>
                <?php
                ++$count;
            endforeach; ?>
            <tr valign="middle" class="other-row">
                <td width="20"><input type="radio" name="payment[card_payment_method_token]" id="other-creditcard" value="other" /></td>
                <td><label for="other-creditcard"><?php echo $this->__('New Credit Card'); ?></label></td>
            </tr>
        </table>

    <?php endif; ?>

    <div id="credit-card-form"<?php echo ($this->hasSavedDetails() && $this->getMethod()->isVaultEnabled() ? ' style="display: none;"' : ''); ?>>
        <ul class="form-list braintree-hostedfield">
            <li>
                <label for="card-number"><?php echo $this->__('Card Number'); ?></label>
                <div class="card-input braintree-card-input-field">
                    <div class="card-type"><img src="<?php echo $this->getSkinUrl('images/gene/braintree/card.png') ?>" id="card-type-image" /></div>
                    <div id="card-number"></div>
                </div>
            </li>
            <li>
                <label for="expiration-month"><?php echo $this->__('Expiration Date'); ?></label>
                <div id="braintree-expiration-container">
                    <div id="expiration-month" class="braintree-input-field braintree-expiration"></div>
                    <div class="braintree-expiration-seperator">/</div>
                    <div id="expiration-year" class="braintree-input-field braintree-expiration"></div>
                </div>
            </li>
            <?php echo $this->getChildHtml() ?>
            <?php if($this->hasVerification()): ?>
                <li>
                    <label for="cvv"><?php echo $this->__('CVV'); ?></label>
                    <div id="cvv" class="braintree-input-field braintree-cvv"></div>
                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                </li>
            <?php endif; ?>
            <?php if ($this->canSaveCard()): ?>
                <li id="<?php echo $_code ?>_store_in_vault_div">
                    <input type="checkbox" title="<?php echo $this->__('Save this card for future use') ?>"
                           class="input-checkbox" id="<?php echo $_code ?>_store_in_vault" name="payment[save_card]"
                           value="1"/>
                    <label for="<?php echo $_code ?>_store_in_vault" style="float:none;"><?php echo $this->__(
                            'Save this card for future use'
                        ) ?></label>
                </li>
            <?php endif; ?>
        </ul>
    </div>

    <?php /* Do not remove or modify this code, the div is hidden and used to fire the hosted fields tokenization */ ?>
    <div id="braintree-hosted-submit">
        <button type="submit" data-blockCapture="true"></button>

        <!-- Fields for the payment method -->
        <input type="text" name="payment[payment_method_nonce]" value="" id="creditcard-payment-nonce" class="validate-fire-hosted" />
    </div>
</div>

<script type="text/javascript">
    if(typeof vzero !== 'undefined') {
        vzero.creditCardLoaded();
    }
</script>